apiVersion: v1
kind: Namespace
metadata:
  name: python-cbs

---

apiVersion: v1
kind: Service
metadata:
  name: python-test-service
  namespace: python-cbs
spec:
  selector:
    app: python-test
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-deployment
  namespace: python-cbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
        - name: python-test-container
          image: cbshaik.jfrog.io/cbsdocker-docker/python-test:v1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-pvc

---
