apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test-app
  template:
    metadata:
      labels:
        app: python-test-app
    spec:
      containers:
      - name: python-test-container
        image: cbshaik.jfrog.io/cbsdocker-docker/python-test1:v1
      imagePullSecrets:
      - name: jfrog-registry
        volumeMounts:
        - name: secret-volume
          mountPath: "/run/secrets/"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: cxtenantsecretsnew
